Adjective1 = input("Tell me an adjective and press enter.")
Adjective2 = input("Give me another adjective.")
Adjective3 = input("One more adjective")
Noun1 = input("Hit me with a noun")
Noun2 = input("Another noun")
Number1= input("Give me a number")
Number2= input("Another Number")
Partofbody= input("What's a part of the body?")
Personyouknow = input("Who is someone you know?")
Pluralnoun1 = input("Plural Noun?")
Pluralnoun2 = input("Another Plural noun?")
Pluraloccupation = input("Plural occupation?")

print("Many future big league baseball" + ' ' + Pluralnoun1 +  ' ' + "Are being trained in little league today. The little leaguers are just like the big league" + ' ' + Pluralnoun2 + ' ' + "Except that the players are all between" + ' ' + Number1 + "and" + Number2 + "years old. When a" + Noun1 + ".goes out for a Little League team, he is given" + Adjective1 + ".tests in fielding fast" + Pluralnoun2)
